### ISSUE TITLE
发现一个闪退的bug

### ISSUE THREAD

**Issue by Lsy1992** [YoKeyword/IndexableStickyListView#17]
该情况再"选择联系人DEMO"模块偶尔会出现，以下是错误日志
`
09-13 18:20:08.708 25468-25468/com.yokeyword.indexablelistview.sample E/InputEventReceiver: Exception dispatching input event.
09-13 18:20:08.708 25468-25468/com.yokeyword.indexablelistview.sample E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
09-13 18:20:08.709 25468-25468/com.yokeyword.indexablelistview.sample E/MessageQueue-JNI: java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
                                                                                              at java.util.ArrayList.get(ArrayList.java:310)
                                                                                              at me.yokeyword.indexablelistview.IndexBar.processOverlayView(IndexBar.java:184)
                                                                                              at me.yokeyword.indexablelistview.IndexBar.onTouchEvent(IndexBar.java:143)
                                                                                              at android.view.View.dispatchTouchEvent(View.java:8668)
                                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2114)
                                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2114)
                                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2114)
                                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2114)
                                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2114)
                                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2114)
                                                                                              at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                                              at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2114)
                                                                                              at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2539)
                                                                                              at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1807)
                                                                                              at android.app.Activity.dispatchTouchEvent(Activity.java:2823)
                                                                                              at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                                              at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2496)
                                                                                              at android.view.View.dispatchPointerEvent(View.java:8874)
                                                                                              at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4724)
                                                                                              at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4582)
                                                                                              at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4081)
                                                                                              at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4134)
                                                                                              at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4100)
                                                                                              at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4237)
                                                                                              at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4108)
                                                                                              at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4294)
                                                                                              at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4081)
                                                                                              at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4134)
                                                                                              at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4100)
                                                                                              at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4108)
                                                                                              at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4081)
                                                                                              at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6538)
                                                                                              at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6512)
                                                                                              at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6465)
                                                                                              at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6718)
                                                                                              at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                                              at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                              at android.os.MessageQueue.next(MessageQueue.java:148)
                                                                                              at android.os.Looper.loop(Looper.java:151)
                                                                                              at android.app.ActivityThread.main(ActivityThread.java:5824)
                                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1010)
                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
09-13 18:20:08.710 25468-25468/com.yokeyword.indexablelistview.sample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                        Process: com.yokeyword.indexablelistview.sample, PID: 25468
                                                                                        java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
                                                                                            at java.util.ArrayList.get(ArrayList.java:310)
                                                                                            at me.yokeyword.indexablelistview.IndexBar.processOverlayView(IndexBar.java:184)
                                                                                            at me.yokeyword.indexablelistview.IndexBar.onTouchEvent(IndexBar.java:143)
                                                                                            at android.view.View.dispatchTouchEvent(View.java:8668)
                                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2114)
                                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2114)
                                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2114)
                                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2114)
                                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2114)
                                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2114)
                                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2114)
                                                                                            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2539)
                                                                                            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1807)
                                                                                            at android.app.Activity.dispatchTouchEvent(Activity.java:2823)
                                                                                            at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                                            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2496)
                                                                                            at android.view.View.dispatchPointerEvent(View.java:8874)
                                                                                            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4724)
                                                                                            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4582)
                                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4081)
                                                                                            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4134)
                                                                                            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4100)
                                                                                            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4237)
                                                                                            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4108)
                                                                                            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4294)
                                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4081)
                                                                                            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4134)
                                                                                            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4100)
                                                                                            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4108)
                                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4081)
                                                                                            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6538)
                                                                                            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6512)
                                                                                            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6465)
                                                                                            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6718)
                                                                                            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                                            at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                            at android.os.MessageQueue.next(MessageQueue.java:148)
                                                                                            at android.os.Looper.loop(Looper.java:151)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5824)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1010)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
09-13 18:20:09.069 1770-1841/? E/CellLocation: create GsmCellLocation
09-13 18:20:09.244 25904-25931/? E/GED: Failed to get GED Log Buf, err(0)
`

**Comment by YoKeyword** [comment]
是最新版的吗？  我暂时无法复现，具体什么操作引起的呢

**Comment by Lsy1992** [comment]
是最新版的，联系人界面，进入出去来回切换，并且手指在界面滑动，有概率出现此bug

**Comment by YoKeyword** [comment]
好的 我回头排查下 🙏

**Comment by Lsy1992** [comment]
谢谢，已经在项目中使用了非常棒，希望可以早日发现修复这个bug

**Comment by Lsy1992** [comment]
你好，这个bug经过我多次尝试发现了一个百分比会复现的操作：
 进入联系人界面，在数据还没加载完毕之前，(一进去界面就快速摸向索引条) 手指触摸在右侧索引条的位置，几乎是每次都闪退。麻烦查看一下

**Comment by YoKeyword** [comment]
太感谢了，已修复～   🙏
