### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by linshiyx** [YoKeyword/IndexableStickyListView#6]
您好,使用时报错:
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
                                                                                 at android.view.ViewGroup.addViewInner(ViewGroup.java:3938)
                                                                                 at android.view.ViewGroup.addView(ViewGroup.java:3788)
                                                                                 at android.view.ViewGroup.addView(ViewGroup.java:3729)
                                                                                 at me.yokeyword.indexablelistview.IndexableStickyListView.updateListView(IndexableStickyListView.java:465)
                                                                                 at me.yokeyword.indexablelistview.IndexableStickyListView.access$400(IndexableStickyListView.java:35)
                                                                                 at me.yokeyword.indexablelistview.IndexableStickyListView$BindDatasHanlder$1.run(IndexableStickyListView.java:278)
                                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

请问这个该怎么解决

**Comment by YoKeyword** [comment]
@linshiyx  是最新版  在多次绑定数据时发生的吗？  我后天回去再看下哈 :)

**Comment by linshiyx** [comment]
好了我知道问题了....
onCreateTitleViewHolder
这个里面inflate的视图的xml不能有layout只能是一个textview

**Comment by YoKeyword** [comment]
好的 目前库可能还有些局限性，后续会持续维护 :)

**Comment by linshiyx** [comment]
谢谢分享,继续支持~

**Comment by linshiyx** [comment]
额 需要支持搜索的话,还得给继承IndexEntity的类的构造函数加一句super(name)吧,希望注释里可以提一句,照顾一下我们小白...

**Comment by YoKeyword** [comment]
如果是需要复写IndexEntity(String name)带name的构造参数，就需要加super(name)      :)
