### ISSUE TITLE
Crash[The content of the adapter has changed but ListView did not receive a notification.]

### ISSUE THREAD

**Issue by baiguangyuan** [YoKeyword/IndexableStickyListView#7]
例子中的：
点击[选择联系人DEMO] --> back --> 点击[选择联系人DEMO] , 几次就会crash。麻烦查下 
设备：HM NOTE1
日志：
*******************************************************************************************************************************
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.yokeyword.indexablelistview.sample, PID: 5812
                  java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(-1, class android.widget.ListView) with Adapter(class android.widget.HeaderViewListAdapter)]
                      at android.widget.ListView.layoutChildren(ListView.java:1555)
                      at android.widget.AbsListView.onLayout(AbsListView.java:2089)
                      at android.view.View.layout(View.java:14845)
                      at android.view.ViewGroup.layout(ViewGroup.java:4631)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                      at android.view.View.layout(View.java:14845)
                      at android.view.ViewGroup.layout(ViewGroup.java:4631)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                      at android.view.View.layout(View.java:14845)
                      at android.view.ViewGroup.layout(ViewGroup.java:4631)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                      at android.view.View.layout(View.java:14845)
                      at android.view.ViewGroup.layout(ViewGroup.java:4631)
                      at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:435)
                      at android.view.View.layout(View.java:14845)
                      at android.view.ViewGroup.layout(ViewGroup.java:4631)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                      at android.view.View.layout(View.java:14845)
                      at android.view.ViewGroup.layout(ViewGroup.java:4631)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                      at android.view.View.layout(View.java:14845)
                      at android.view.ViewGroup.layout(ViewGroup.java:4631)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                      at android.view.View.layout(View.java:14845)
                      at android.view.ViewGroup.layout(ViewGroup.java:4631)
                      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2030)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1787)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1043)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5652)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                      at android.view.Choreographer.doFrame(Choreographer.java:544)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                      at android.os.Handler.handleCallback(Handler.java:733)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5113)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                      at dalvik.system.NativeStart.main(Native Method)

**Comment by YoKeyword** [comment]
感谢反馈🙏  
我来看看哈  我的红米Note测试机也确实重现了这个异常～

**Comment by YoKeyword** [comment]
@baiguangyuan 已经解决，push了0.6.3版本
原因是给ListView addHeaderView时，Adapter会被转成HeaderViewListAdapter，在快速BACK时，校验ItemCount时出现了问题。
🙏
